version: "3.9"
services:

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "books"
      POSTGRES_USER: "username"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"

volumes:
  cache:
    driver: local